/*
 * Copyright (c) 2024 Your Name
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none


module tt_um_llr_simplenpu (
    input  wire [7:0] ui_in,    // Dedicated inputs
    output wire [7:0] uo_out,   // Dedicated outputs
    input  wire [7:0] uio_in,   // IOs: Input path
    output wire [7:0] uio_out,  // IOs: Output path
    output wire [7:0] uio_oe,   // IOs: Enable path (active high: 0=input, 1=output)
    input  wire       ena,      // always 1 when the design is powered, so you can ignore it
    input  wire       clk,      // clock
    input  wire       rst_n     // reset_n - low to reset
);

  // All output pins must be assigned. If not used, assign to 0.
  //assign uo_out  = ui_in + uio_in;  // Example: ou_out is the sum of ui_in and uio_in
  assign uio_oe[7:4]  = 0;

  // List all unused inputs to prevent warnings
  wire _unused = &{ena, 1'b0};

  wire project_extflash_spi_cs;
  wire project_extflash_spi_mosi;
  wire project_extflash_spi_miso;
  wire project_extflash_spi_sck;

  assign uio_out[2:0] = {project_extflash_spi_cs, project_extflash_spi_mosi, project_extflash_spi_sck};
  assign uio_out[7:3] = 0;
  assign uio_oe[2:0] = 3'b111;
  assign uio_oe[3] = 1'b0;




  simple_npu_top simpleNPUTop (
  .CLK(clk),
  .rst_n_ext(rst_n),
  .extflash_spi_cs(project_extflash_spi_cs),
  .extflash_spi_mosi(project_extflash_spi_mosi),
  .extflash_spi_miso(uio_in[3]),
  .extflash_spi_sck(project_extflash_spi_sck),

  .data_input(ui_in[3:0]),
  .data_addr(ui_in[6:4]),
  .data_save_btn(ui_in[7]),

  .act_out_leds(uo_out[3:0]),
  .act_out_leds2(uo_out[7:4])
);
endmodule


// generated by claude
function automatic [3:0] ComputeActivation(input [3:0] activation_input, input [2:0] act_fun);
  logic signed [3:0] x;

  begin
    x = activation_input; // signed view, range -8..+7

    case (act_fun)
      // ---- linear / trivial ----
      3'b000: ComputeActivation = activation_input;                                   // identity
      3'b001: ComputeActivation = (activation_input[3]) ? 4'b0000 : activation_input;  // ReLU
      3'b010: ComputeActivation = (activation_input[3]) ? 4'b0000 : 4'b0001;           // step / sign
      3'b011: ComputeActivation = (activation_input[3]) ? (~activation_input + 4'b0001) : activation_input; // |x|
      3'b100: ComputeActivation = ~activation_input + 4'b0001;                        // negation

      // ---- cheap nonlinear approximations (shift/add/compare only) ----

      // hard sigmoid: y = x/2 + 8  (arithmetic shift + add; range works out to 0..15 with no clamp needed)
      3'b101: ComputeActivation = (x >>> 1) + 4'sd8;

      // saturating "gain-2" soft-tanh: y = 2x, clamped to [-8,7]
      3'b110: if (x >= 4)       ComputeActivation = 4'd7;
              else if (x <= -5) ComputeActivation = 4'b1000;
              else              ComputeActivation = x + x;

      // small LUT sigmoid: only 16 possible inputs exist, so an exact table beats
      // any shift/add formula in accuracy while costing the same (a 16-entry ROM/case)
      3'b111: case (activation_input)
                4'b1000: ComputeActivation = 4'd2;  // x=-8
                4'b1001: ComputeActivation = 4'd2;  // x=-7
                4'b1010: ComputeActivation = 4'd3;  // x=-6
                4'b1011: ComputeActivation = 4'd4;  // x=-5
                4'b1100: ComputeActivation = 4'd4;  // x=-4
                4'b1101: ComputeActivation = 4'd5;  // x=-3
                4'b1110: ComputeActivation = 4'd6;  // x=-2
                4'b1111: ComputeActivation = 4'd7;  // x=-1
                4'b0000: ComputeActivation = 4'd8;  // x= 0
                4'b0001: ComputeActivation = 4'd9;  // x= 1
                4'b0010: ComputeActivation = 4'd10; // x= 2
                4'b0011: ComputeActivation = 4'd11; // x= 3
                4'b0100: ComputeActivation = 4'd12; // x= 4
                4'b0101: ComputeActivation = 4'd12; // x= 5
                4'b0110: ComputeActivation = 4'd13; // x= 6
                4'b0111: ComputeActivation = 4'd14; // x= 7
                default: ComputeActivation = 4'd8;
              endcase

      default: ComputeActivation = 4'b0000; // avoids latch inference
    endcase
  end
endfunction

  // NOTE: to make compatible with windbond flash = would only need to make addr 24 bit
  typedef enum logic[3:0] {
  STATE_INPUT_VALUES,

  STATE_SPI_RD,
  STATE_SPI_ADDRBANK,
  STATE_SPI_ADDR0, STATE_SPI_ADDR1, // send addr MSB, then LSB
  STATE_SPI_FETCH_INSTRUCTION,

  // this block is repeated 8 times for each neurons
  STATE_INSTRUCTION_CALC_FETCH_WEIGHTS, // have counter alongside for 4 weights
  STATE_INSTRUCTION_CALC_COMPUTEMULACC, // latch 
  STATE_INSTRUCTION_CALC_COMPUTE_ACTFUNC,

  STATE_INSTRUCTION_END // only release CS there
  } exec_state;

module simple_npu_top (
  input wire CLK,
  input wire rst_n_ext,
  output reg extflash_spi_cs,
  output wire extflash_spi_mosi,
  input wire extflash_spi_miso,
  output wire extflash_spi_sck,

  input [3:0] data_input,
  input [2:0] data_addr,
  input data_save_btn,

  output [3:0] act_out_leds,
  output [3:0] act_out_leds2
);
wire rst_n = rst_n_ext;


  wire SPI_BUSY;
  wire SPI_DONE = ~SPI_BUSY;
  reg [7:0] SPI_DATA_MOSI;
  wire [7:0] SPI_DATA_MISO;

  reg SPI_SEND_DATA;

  reg SPI_SEND_DATA_PULSE;
  reg SPI_SEND_DATA_OLD;
  reg SPI_DONE_PULSE;
  reg SPI_DONE_OLD;

  always_ff @(posedge CLK or negedge rst_n) begin
    if(~rst_n) begin
      SPI_SEND_DATA_PULSE <= 1'b0;
      SPI_SEND_DATA_OLD <= 1'b0;
    end else begin
      SPI_SEND_DATA_OLD <= SPI_SEND_DATA;
      SPI_SEND_DATA_PULSE <= (~SPI_SEND_DATA_OLD && SPI_SEND_DATA);
     // if(~SPI_SEND_DATA_OLD && SPI_SEND_DATA) begin
     //   SPI_SEND_DATA_PULSE <= 1'b1;
     // end else if(~extflash_spi_cs) begin//SPI_DONE) begin //SPI_DONE_PULSE) begin
     //   SPI_SEND_DATA_PULSE <= 1'b0; 
     // end
    end
  end



  wire [15:0] flash_addr = 16'h0000;

  reg signed [7:0][3:0] activations_out_memory;
  reg signed [7:0][3:0] activations_tmp;
  reg signed [7:0][3:0] weights;
  reg [7:0] instruction;
  wire [3:0] bais;
  assign bais = instruction[3:0];
  wire [2:0] act_function;
  assign act_function = instruction[6:4];
  
  wire [3:0] act_calc_out;
  reg [3:0] tmp_activation;

  weight_compute wc(
    .prev_activation(activations_out_memory),
    .weight(weights),
    .bais(bais),
    .act_out(act_calc_out)
  );

  exec_state currentState;

  
  reg data_save_pulse;
  reg data_save_old;


  reg [2:0] calc_current_neuron;
  reg [1:0] weight_fetch_index;

  wire debug_CALC_COMPUTEMULACC_pulse = (currentState == STATE_INSTRUCTION_CALC_COMPUTEMULACC);
  wire debug_DONE = (currentState == STATE_INSTRUCTION_END);

  integer i;

  always_ff @(posedge CLK or negedge rst_n) begin
    if(~rst_n) begin
      currentState <= STATE_INPUT_VALUES;
      SPI_SEND_DATA <= 1'b0;

      extflash_spi_cs <= 1'b1;

      calc_current_neuron <= 3'h0;
      weight_fetch_index <= 2'b00;

      for(i = 0; i < 8; i = i + 1) begin
          activations_out_memory[i] <= 0;
          activations_tmp[i] <= 0;
          weights[i] <= 0;
      end

    end else begin
    data_save_pulse <= ~data_save_old && data_save_btn;
    data_save_old <= data_save_btn;


    case (currentState)
        STATE_INPUT_VALUES : begin
          if(data_save_pulse) begin
            activations_out_memory[data_addr] <= data_input;
            if(data_addr == 3'b111) begin
              currentState <= STATE_SPI_RD;
            end
          end
        end

        STATE_SPI_RD: begin
          if(SPI_DONE_PULSE) begin
            currentState <= STATE_SPI_ADDRBANK;
            SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= 8'h03; // READ command
            SPI_SEND_DATA <= 1'b1;
            extflash_spi_cs <= 1'b0;
          end
        end

        STATE_SPI_ADDRBANK: begin
          if(SPI_DONE_PULSE) begin
            currentState <= STATE_SPI_ADDR0;
            SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= 8'h00; // addr[23:16]
            SPI_SEND_DATA <= 1'b1;
          end
        end

        STATE_SPI_ADDR0: begin
          if(SPI_DONE_PULSE) begin
            currentState <= STATE_SPI_ADDR1;
            SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= flash_addr[15:8]; // addr[15:8] command
            SPI_SEND_DATA <= 1'b1;
          end
        end
 
        STATE_SPI_ADDR1:  begin
          if(SPI_DONE_PULSE) begin
            currentState <= STATE_SPI_FETCH_INSTRUCTION;
            SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= flash_addr[7:0]; // addr[15:8] command
            SPI_SEND_DATA <= 1'b1;
          end
        end

 
        STATE_SPI_FETCH_INSTRUCTION: begin
          weight_fetch_index <= 2'b00;

          if(SPI_DONE_PULSE) begin
            instruction = SPI_DATA_MISO;

            if(instruction[7] == 1'b1) begin
              currentState <= STATE_INSTRUCTION_END;
              extflash_spi_cs <= 1'b1;
            end else begin
              currentState <= STATE_INSTRUCTION_CALC_FETCH_WEIGHTS;
            end

            SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= 8'hFF; // dummy data for read
            SPI_SEND_DATA <= 1'b1;
          end
        end

        STATE_INSTRUCTION_CALC_FETCH_WEIGHTS: begin
            if(SPI_DONE_PULSE) begin
              weight_fetch_index <= weight_fetch_index + 1;

              weights[2*weight_fetch_index] <= SPI_DATA_MISO[7:4];
              weights[(2*weight_fetch_index) + 1] <= SPI_DATA_MISO[3:0];

              if(weight_fetch_index == 2'b11) begin
                currentState <= STATE_INSTRUCTION_CALC_COMPUTEMULACC;
              end

              SPI_SEND_DATA <= 1'b0;
          end else begin
            SPI_DATA_MOSI <= 8'hFF; // dummy data for read
            SPI_SEND_DATA <= 1'b1;
          end
        end

        STATE_INSTRUCTION_CALC_COMPUTEMULACC: begin
          tmp_activation <= act_calc_out;
          currentState <= STATE_INSTRUCTION_CALC_COMPUTE_ACTFUNC;
        end

        STATE_INSTRUCTION_CALC_COMPUTE_ACTFUNC: begin
          calc_current_neuron <= calc_current_neuron + 1;

          activations_tmp[calc_current_neuron] = ComputeActivation(tmp_activation, act_function);

          if(calc_current_neuron == 3'b111) begin
            calc_current_neuron <= 3'h0;

            for(i = 0; i < 8; i = i + 1) begin
                activations_out_memory[i] <= activations_tmp[i];
                weights[i] <= 0;
            end
          end
        
            currentState <= STATE_SPI_FETCH_INSTRUCTION;
        end

      STATE_INSTRUCTION_END: begin
          if(data_save_pulse) begin
            currentState <= STATE_INPUT_VALUES;
          end
      end

        default: currentState <= STATE_SPI_RD;
    endcase
  end
  end

  assign act_out_leds = activations_out_memory[data_addr];
  assign act_out_leds2 = activations_tmp[data_addr];



  wire SPI_CLK;

   spi_master #(
    .CLK_DIV(1)   // SCLK = clk / (2*CLK_DIV)
   ) spiMaster (
     .clk(CLK),
     .rst_n(rst_n),   // async, active-low

      .cs_n(),
     .sclk(extflash_spi_sck),
     .mosi(extflash_spi_mosi),
     .miso(extflash_spi_miso),

     .send(SPI_SEND_DATA_PULSE),
     .din(SPI_DATA_MOSI),
     .dout(SPI_DATA_MISO),
    .done(SPI_DONE_PULSE),
    .busy(SPI_BUSY)
);

endmodule
